import { Recipe, MoodOption } from './types';

export type { MoodOption };

export const MOODS: MoodOption[] = [
  { id: 'brain_dead', label: 'Brain Dead', emoji: '⚡', description: '5–10 min meals', maxMinutes: 10 },
  { id: 'quick_win', label: 'Quick Win', emoji: '🍳', description: '15 min meals', maxMinutes: 20 },
  { id: 'proper_cooking', label: 'Proper Cooking', emoji: '👨‍🍳', description: '30–45 min meals', maxMinutes: 45 },
  { id: 'impress_someone', label: 'Impress Someone', emoji: '❤️', description: 'Fancier meals', maxMinutes: 90 },
];

export const LOADING_MESSAGES = [
  'Consulting the Spice Gods…',
  'Negotiating with your leftovers…',
  'Dinner destiny loading…',
  'Checking the back of your pantry…',
  'Bribing the fridge magnets…',
  'Calculating deliciousness…',
  'Asking your grandma (virtually)…',
  'Matching vibes with your veggies…',
];

export const RECIPES: Recipe[] = [
  {
    id: 'scrambled-eggs',
    name: 'Perfect Scrambled Eggs',
    emoji: '🍳',
    time: 8,
    requiredIngredients: ['egg'],
    optionalIngredients: ['cheese', 'spinach'],
    description: 'Creamy, fluffy scrambled eggs — the ultimate lazy comfort.',
    steps: [
      { id: 1, title: 'Crack & whisk', instruction: 'Crack 3 eggs into a bowl. Add a pinch of salt and whisk until pale and frothy.', timerSeconds: null },
      { id: 2, title: 'Heat the pan', instruction: 'Put a small knob of butter in a non-stick pan over medium-low heat.', timerSeconds: 60 },
      { id: 3, title: 'Cook slowly', instruction: 'Pour in eggs. Stir gently with a spatula, pulling from the edges. Keep heat low!', timerSeconds: 180 },
      { id: 4, title: 'Finish strong', instruction: 'Remove from heat while still slightly wet — they keep cooking on their own. Season and serve immediately.', timerSeconds: null },
    ],
    substitutions: [],
    moodFit: ['brain_dead', 'quick_win'],
  },
  {
    id: 'tomato-pasta',
    name: 'Tomato Garlic Pasta',
    emoji: '🍅',
    time: 20,
    requiredIngredients: ['pasta', 'tomato'],
    optionalIngredients: ['cheese', 'spinach', 'onion'],
    description: 'A dead-simple Italian classic. Five ingredients, maximum impact.',
    steps: [
      { id: 1, title: 'Boil water', instruction: 'Fill a large pot, salt generously, and bring to a boil.', timerSeconds: null },
      { id: 2, title: 'Cook pasta', instruction: 'Add pasta. Cook per package instructions minus 2 minutes — we finish it in the sauce.', timerSeconds: 480 },
      { id: 3, title: 'Sauté', instruction: 'While pasta cooks, warm garlic in olive oil for 30 seconds, then add diced tomatoes. Simmer.', timerSeconds: 300 },
      { id: 4, title: 'Combine', instruction: 'Drain pasta (save a cup of pasta water!), add to sauce, toss vigorously. Add water to loosen.', timerSeconds: null },
      { id: 5, title: 'Serve', instruction: 'Top with cheese and torn spinach if you have it. Eat immediately.', timerSeconds: null },
    ],
    substitutions: [{ missing: 'garlic', have: 'onion', advice: 'Use half an onion instead — cook a little longer for sweetness.' }],
    moodFit: ['quick_win', 'proper_cooking'],
  },
  {
    id: 'chicken-fried-rice',
    name: 'Chicken Fried Rice',
    emoji: '🍗',
    time: 25,
    requiredIngredients: ['chicken', 'rice'],
    optionalIngredients: ['egg', 'onion', 'spinach'],
    description: 'Better than takeout. Seriously. Your wok will thank you.',
    steps: [
      { id: 1, title: 'Dice chicken', instruction: 'Cut chicken into small bite-sized cubes. Season with salt and pepper.', timerSeconds: null },
      { id: 2, title: 'Fry chicken', instruction: 'Hot pan, oil in, chicken in. Fry 5–6 minutes until golden. Remove and set aside.', timerSeconds: 360 },
      { id: 3, title: 'Sauté onion', instruction: 'In the same pan, fry diced onion for 2 minutes until translucent.', timerSeconds: 120 },
      { id: 4, title: 'Add rice', instruction: 'Tip in cold cooked rice. Stir fry on high heat, spreading across the pan.', timerSeconds: 180 },
      { id: 5, title: 'Add egg', instruction: 'Push rice to the side. Crack in 2 eggs, scramble, then mix through the rice.', timerSeconds: 60 },
      { id: 6, title: 'Sauce & finish', instruction: 'Add soy sauce and any greens. Toss everything together. Add back the chicken. Eat hot.', timerSeconds: null },
    ],
    substitutions: [{ missing: 'soy_sauce', have: 'salt', advice: 'Use extra salt and a tiny splash of vinegar for that umami depth.' }],
    moodFit: ['quick_win', 'proper_cooking'],
  },
  {
    id: 'cheese-toast',
    name: 'Legendary Cheese Toast',
    emoji: '🧀',
    time: 7,
    requiredIngredients: ['bread', 'cheese'],
    optionalIngredients: ['tomato', 'egg'],
    description: 'The meal that never fails. Crispy, melty, perfect.',
    steps: [
      { id: 1, title: 'Prep slice', instruction: 'Place bread on a baking tray. Optionally add a slice of tomato on top.', timerSeconds: null },
      { id: 2, title: 'Load cheese', instruction: 'Pile on cheese. Don\'t be shy. This is your moment.', timerSeconds: null },
      { id: 3, title: 'Grill it', instruction: 'Pop under the grill (or in a toaster oven) until cheese is bubbling and edges are golden.', timerSeconds: 300 },
      { id: 4, title: 'Enjoy', instruction: 'Let it cool 30 seconds (seriously, it\'s molten). Then devour.', timerSeconds: 30 },
    ],
    substitutions: [],
    moodFit: ['brain_dead'],
  },
  {
    id: 'potato-wedges',
    name: 'Crispy Potato Wedges',
    emoji: '🥔',
    time: 40,
    requiredIngredients: ['potato'],
    optionalIngredients: ['cheese'],
    description: 'The kind of potatoes that make you forget everything else.',
    steps: [
      { id: 1, title: 'Preheat', instruction: 'Heat oven to 220°C (fan 200°C). Line a baking tray with foil.', timerSeconds: null },
      { id: 2, title: 'Cut wedges', instruction: 'Quarter potatoes lengthways. Toss in olive oil, salt, pepper, and any spices you fancy.', timerSeconds: null },
      { id: 3, title: 'Bake', instruction: 'Spread in a single layer, skin-side down. Bake 35 minutes, flipping halfway.', timerSeconds: 2100 },
      { id: 4, title: 'Serve', instruction: 'They\'re done when the edges are crunchy and the inside is fluffy. Serve with anything.', timerSeconds: null },
    ],
    substitutions: [],
    moodFit: ['proper_cooking'],
  },
  {
    id: 'spinach-egg-frittata',
    name: 'Spinach Frittata',
    emoji: '🥬',
    time: 18,
    requiredIngredients: ['egg', 'spinach'],
    optionalIngredients: ['cheese', 'onion', 'tomato'],
    description: 'A one-pan Italian egg bake that feels fancy but is secretly easy.',
    steps: [
      { id: 1, title: 'Sauté vegetables', instruction: 'Cook onion and spinach in olive oil over medium heat for 3 minutes.', timerSeconds: 180 },
      { id: 2, title: 'Whisk eggs', instruction: 'Beat 4 eggs with salt, pepper, and cheese. Pour over vegetables in the pan.', timerSeconds: null },
      { id: 3, title: 'Cook base', instruction: 'Cook on medium-low for 4 minutes until the edges set.', timerSeconds: 240 },
      { id: 4, title: 'Oven finish', instruction: 'Transfer to a 180°C oven for 8 minutes or grill until top is golden.', timerSeconds: 480 },
    ],
    substitutions: [{ missing: 'spinach', have: 'tomato', advice: 'Slice tomatoes and arrange on top before baking — beautiful and delicious.' }],
    moodFit: ['quick_win', 'proper_cooking'],
  },
  {
    id: 'chicken-onion-pasta',
    name: 'Chicken & Onion Pasta Bake',
    emoji: '🍝',
    time: 40,
    requiredIngredients: ['chicken', 'pasta', 'onion'],
    optionalIngredients: ['cheese', 'tomato', 'spinach'],
    description: 'A proper weeknight bake. Best eaten in massive portions.',
    steps: [
      { id: 1, title: 'Boil pasta', instruction: 'Cook pasta until just under al dente. Drain and set aside.', timerSeconds: 480 },
      { id: 2, title: 'Cook chicken', instruction: 'Fry diced chicken with onion in olive oil until the chicken is golden all over.', timerSeconds: 360 },
      { id: 3, title: 'Make sauce', instruction: 'Add crushed tomatoes (or diced tomato), season well, simmer 5 minutes.', timerSeconds: 300 },
      { id: 4, title: 'Combine & top', instruction: 'Mix pasta into sauce, pour into baking dish, top generously with cheese.', timerSeconds: null },
      { id: 5, title: 'Bake', instruction: 'Bake at 190°C for 20 minutes until top is golden brown.', timerSeconds: 1200 },
    ],
    substitutions: [{ missing: 'tomato', have: 'cheese', advice: 'Skip tomato, use a béchamel-style sauce: butter + flour + milk + cheese.' }],
    moodFit: ['proper_cooking', 'impress_someone'],
  },
  {
    id: 'rice-bowl',
    name: 'Golden Rice Bowl',
    emoji: '🍚',
    time: 15,
    requiredIngredients: ['rice', 'egg'],
    optionalIngredients: ['spinach', 'cheese', 'tomato'],
    description: 'The egg-on-rice combo that Japan perfected. Simple, satisfying, restorative.',
    steps: [
      { id: 1, title: 'Cook rice', instruction: 'Prepare rice per packet or use leftover. Fluff with a fork.', timerSeconds: null },
      { id: 2, title: 'Fry eggs', instruction: 'Fry 2 eggs in butter. You want a crispy white and a runny yolk.', timerSeconds: 180 },
      { id: 3, title: 'Assemble', instruction: 'Place eggs on top of the rice. Add soy sauce, sesame oil if you have it.', timerSeconds: null },
      { id: 4, title: 'Finish', instruction: 'Season liberally and eat immediately. Puncture that yolk with drama.', timerSeconds: null },
    ],
    substitutions: [],
    moodFit: ['brain_dead', 'quick_win'],
  },
  {
    id: 'tomato-egg-shakshuka',
    name: 'Turkish Shakshuka',
    emoji: '🍳',
    time: 22,
    requiredIngredients: ['egg', 'tomato', 'onion'],
    optionalIngredients: ['spinach', 'cheese'],
    description: 'Eggs poached in spiced tomato sauce. Brunch royalty.',
    steps: [
      { id: 1, title: 'Start the sauce', instruction: 'Fry diced onion in olive oil until soft, about 4 minutes. Add spices (cumin, paprika).', timerSeconds: 240 },
      { id: 2, title: 'Add tomatoes', instruction: 'Add crushed or diced tomatoes. Season well. Simmer 8 minutes until thick.', timerSeconds: 480 },
      { id: 3, title: 'Crack eggs', instruction: 'Make wells in the sauce. Crack one egg per well. Add lid and cook 5 minutes.', timerSeconds: 300 },
      { id: 4, title: 'Serve', instruction: 'Whites should be set, yolks runny. Serve with bread to scoop up every drop.', timerSeconds: null },
    ],
    substitutions: [{ missing: 'onion', have: 'garlic', advice: 'Use 3 cloves garlic instead. Fry briefly — it burns faster than onion.' }],
    moodFit: ['quick_win', 'proper_cooking', 'impress_someone'],
  },
  {
    id: 'garlic-bread',
    name: 'Epic Garlic Bread',
    emoji: '🍞',
    time: 12,
    requiredIngredients: ['bread'],
    optionalIngredients: ['cheese'],
    description: 'The side dish that becomes the main event. No apologies.',
    steps: [
      { id: 1, title: 'Make butter', instruction: 'Mash softened butter with minced garlic, salt, and any fresh herbs you have.', timerSeconds: null },
      { id: 2, title: 'Spread', instruction: 'Slice bread and spread garlic butter generously inside.', timerSeconds: null },
      { id: 3, title: 'Bake', instruction: 'Wrap in foil and bake at 180°C for 10 minutes. Open top, bake 2 more for crispiness.', timerSeconds: 720 },
      { id: 4, title: 'Serve', instruction: 'Tear apart and watch everyone fight over the end pieces.', timerSeconds: null },
    ],
    substitutions: [],
    moodFit: ['brain_dead', 'quick_win'],
  },
  {
    id: 'loaded-omelette',
    name: 'Loaded Omelette',
    emoji: '🥚',
    time: 12,
    requiredIngredients: ['egg'],
    optionalIngredients: ['cheese', 'onion', 'spinach', 'tomato'],
    description: 'Fold once. Act like it took effort. Receive compliments.',
    steps: [
      { id: 1, title: 'Prep fillings', instruction: 'Sauté any fillings (onion, tomato, spinach) for 2 minutes. Set aside.', timerSeconds: 120 },
      { id: 2, title: 'Beat eggs', instruction: 'Whisk 3 eggs with a pinch of salt and pepper until just mixed.', timerSeconds: null },
      { id: 3, title: 'Cook base', instruction: 'Melt butter in a non-stick pan over medium heat. Pour in eggs. Tilt to spread.', timerSeconds: 90 },
      { id: 4, title: 'Add fillings', instruction: 'When mostly set but still glossy on top, add fillings and cheese to one half.', timerSeconds: null },
      { id: 5, title: 'Fold & slide', instruction: 'Fold in half. Slide onto a warm plate. Rest 30 seconds before eating.', timerSeconds: 30 },
    ],
    substitutions: [],
    moodFit: ['brain_dead', 'quick_win'],
  },
  {
    id: 'creamy-potato-soup',
    name: 'Creamy Potato Soup',
    emoji: '🥔',
    time: 35,
    requiredIngredients: ['potato', 'onion'],
    optionalIngredients: ['cheese', 'chicken'],
    description: 'Hug in a bowl. Blended, warming, and wildly underrated.',
    steps: [
      { id: 1, title: 'Sauté aromatics', instruction: 'Cook diced onion and garlic in butter over medium heat for 3 minutes.', timerSeconds: 180 },
      { id: 2, title: 'Add potatoes', instruction: 'Add peeled, diced potatoes. Cover with stock or water (about 600ml).', timerSeconds: null },
      { id: 3, title: 'Simmer', instruction: 'Bring to boil, then simmer uncovered for 20 minutes until potatoes are very soft.', timerSeconds: 1200 },
      { id: 4, title: 'Blend', instruction: 'Blend until smooth with a stick blender. Add butter, season well.', timerSeconds: null },
      { id: 5, title: 'Serve', instruction: 'Top with grated cheese, cracked pepper, and serve with crusty bread.', timerSeconds: null },
    ],
    substitutions: [],
    moodFit: ['proper_cooking', 'impress_someone'],
  },
  {
    id: 'chicken-stir-fry',
    name: 'Ginger Chicken Stir Fry',
    emoji: '🍗',
    time: 18,
    requiredIngredients: ['chicken', 'spinach'],
    optionalIngredients: ['onion', 'rice'],
    description: 'Restaurant-quality stir fry in under 20 minutes. High heat. No fear.',
    steps: [
      { id: 1, title: 'Slice thin', instruction: 'Slice chicken into thin strips. The thinner, the faster — and crispier.', timerSeconds: null },
      { id: 2, title: 'Blaze hot', instruction: 'Get your pan/wok smoking hot. Add oil. Let it haze.', timerSeconds: 60 },
      { id: 3, title: 'Fry chicken', instruction: 'Add chicken. Don\'t touch it for 90 seconds to get a sear. Toss and repeat.', timerSeconds: 240 },
      { id: 4, title: 'Add veg', instruction: 'Add spinach and any other veggies. Toss on high heat for 2 minutes.', timerSeconds: 120 },
      { id: 5, title: 'Sauce', instruction: 'Add soy sauce, a squeeze of lemon, and toss. Serve immediately over rice.', timerSeconds: null },
    ],
    substitutions: [{ missing: 'spinach', have: 'onion', advice: 'Slice the onion thinly and stir fry hard — it adds sweetness and texture.' }],
    moodFit: ['quick_win', 'proper_cooking'],
  },
  {
    id: 'caprese-salad',
    name: 'Caprese Salad',
    emoji: '🍅',
    time: 5,
    requiredIngredients: ['tomato', 'cheese'],
    optionalIngredients: [],
    description: 'No cooking required. Somehow still impressive. Italy approves.',
    steps: [
      { id: 1, title: 'Slice', instruction: 'Slice tomatoes and mozzarella into even rounds.', timerSeconds: null },
      { id: 2, title: 'Layer', instruction: 'Alternate tomato and cheese slices on a plate. Fan them out dramatically.', timerSeconds: null },
      { id: 3, title: 'Dress', instruction: 'Drizzle with olive oil and balsamic (vinegar works!). Season with salt and pepper.', timerSeconds: null },
      { id: 4, title: 'Serve', instruction: 'Add fresh basil if you have it. Serve immediately with bread for dipping.', timerSeconds: null },
    ],
    substitutions: [{ missing: 'balsamic', have: 'vinegar', advice: 'A splash of plain vinegar works — add a pinch of sugar to balance it.' }],
    moodFit: ['brain_dead', 'impress_someone'],
  },
];
